---
title: "Topic, Background, Outline"
format: typst
editor: visual
---

## Topic Background

The topic of this capstone is based in linguistics, however there is a cognitive component underlying it. Within linguistics, sentence structures are determined by syntactic analysis.

Language code-switching.

What is the frequency of code-switching at the identified structural types of code-switching? Why does it happen in these positions and can they be predicted using morphosyntactic patterns?

Data: Open source corpora for Spanish and English, this can involve web scrapping for text and discourse. At first glance, social media could be considered but this is unfavorable due to the usage of vernacular language specific to online platforms. A potential source of data is then the Bangor Miami corpus, which has conversation data.

<https://bangortalk.org.uk/>

## Bibliography

This article is zooming out on possible causes for the occurrence of code-switching. It provides background for what is code-switching, where it occurs, and what can trigger it at a social level. This is a foundation of holistic code-switching as a social and psychological process.

Bouchard, M.-E. (2025). Why do they code-switch? Examining code-switching, use of vernacular, and linguistic insecurity in a minority French-speaking context of Canada. Journal of Multilingual & Multicultural Development, 1–16. https://doi.org/10.1080/01434632.2025.2542386

Phillips & Sedarous suggest that bilinguals have a wider range of permissible word orders across languages that do not necessarily adhere to that language's general grammatical structure. In this data analysis, that could mean that patter finding for code-switching is not necessarily in accordance to the known language structure and may show different structure preferences depending on other variables.

Phillips, S. F., & Sedarous, Y. (2026). Finding anchors in code-switching: How nouns guide online processing of nominals across three bilingual groups. Glossa: A Journal of General Linguistics, 11(1). https://doi.org/10.16995/glossa.23254

Chan applies the portmanteau construction as an interpretation for speech formation. In this structure, bilinguals co-activate head-complements reading the phonetic output in both langauges and therefore exhibiting code-switching. In this sense, analysis patterns in corpora, would further reveal the proposed theorical model of linguistics explains code-switching.

Chan B. H. (2015). Portmanteau Constructions, Phrase Structure, and Linearization. *Frontiers in psychology*, *6*, 1851. https://doi.org/10.3389/fpsyg.2015.01851

## Outline

Introduction

The introduction section introduces the disciplines theoretical background that informs the basis for what the results can mean within the field. Code-switching, as defined in cognitive science, is an aspect of bilingualism, therefore what informs this paper is the language processes theorized to be engaged when the code-switch is happening.

- Bilingualism Experience

  - Co-activation theory

- Code-switching

  - Code-switching defined

  - As seen in spoken language

    - Discuss phonetic cues (and whatever else applies)

  - As seen in written language

    - Discuss syntactic/lexical cues

    - Introduce the idea behind the research performed by Zirnstein

- The current analysis

  - Research Question(s)

  - Importance

Methods

Methodology then works to explain the two data sources I am working with (maybe introducing the data should happen ealier on?). My first work is with a language corpus that through analysis might inform how language functions naturally. It is sort of working backwards to see what is found through the experimental data is indeed naturally induced in everyday language use (observational data).

- Miami Spanish-English Bilingual Corpus

  - Background information  - access and permutation performed

  - Syntactic

  - Lexical

- Experimental Data

  - Study Design

    - Sampling + location

  - Time of data collection

  - Materials

  - Peripheral

Analysis 1 (Corpus)

Analysis 2 (Experimental)

Results

Discussion

- interpretation of joint data findings (how do the analysis in one connect to the other or reveal something that is not clear in the other)
